server:
  port: 8060

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
  config:
    import: optional:configserver:http://localhost:8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
